### ISSUE TITLE
Understanding the best way to access a mount from both the host and another container

### ISSUE THREAD

**Issue by CraftyClown** [hotio/docker-rclone#9]
Hi there,

I'm just about to move my rclone installation over to your container and I wanted to double check on the best way to mount a volume

I want to access the mount directly from the host machine using sftp, but I also need other containers to access it as well.

So if I've understood your notes on 'Using a rclone mount on the host' correctly, would I be better mounting with bind propagation set to :shared or :slave?

**Comment by CraftyClown** [comment]
Actually I think I did misread. Do I use :shared for the mount point on the rclone container and then :slave to access the same mountpoint from all the other containers?

**Comment by hotio** [comment]
yes, but the ones with `:slave` you should do that on the parent folder of the rclone mount, that way you can restart the rclone mount without having to restart the other containers....

`:shared` just shares the mount back to the host.

**Comment by CraftyClown** [comment]
Ok, so just so I understand, if I want my rclone mount to be located at /mnt/Skull then in the rclone container I would set the volume as -v /mnt/Skull:/mnt/Skull:shared and then for each container that I want to give access to the mount I would use -v /mnt:/mnt:slave

Have I understood this correctly?

**Comment by hotio** [comment]
yes
